help:
	@grep '####' Makefile | grep -v grep | sed -e 's/####//'

cart: ####\t Setup Cart Component
	@bash components/cart.sh

catalogue: #### Setup Catalogue Component
	@bash components/catalogue.sh

user: ####\t Setup User Component
	@bash components/user.sh

shipping: #### Setup Shipping Component
	@bash components/shipping.sh

payment: #### Setup Payment Component
	@bash components/payment.sh

frontend: #### Setup Frontend Component
	@bash components/frontend.sh

mysql: ####\t Setup MySQL Component
	@bash components/mysql.sh

redis: ####\t Setup Redis Component
	@bash components/redis.sh

rabbitmq: #### Setup RabbitMQ Component
	@bash components/rabbitmq.sh

mongodb: #### Setup MongoDB Component
	@bash components/mongodb.sh
